/* GENERATED by schwung-canvaskit v19 — DO NOT EDIT THIS FILE.
 * Source of truth: the module's canvas config + the kit core. Rebuild with:
 *   node ../../schwung-canvaskit/build.mjs canvas.config.js <this file>
 * Chassis: movy-hybrid Bank Editor (widget language adapted from
 * schwung-movy, MIT (c) 2026 megadake; fonts via echidna/davebox mcufont).
 * Loaded by the host as canvas.js#bank_editor. Jog = banks (no overlay);
 * SHIFT+jog = section picker; knobs CC 71-78 edit the active bank. */
(function () {

/* ==== schwung-canvaskit core: prelude ====
 * Fonts, pure input helpers, and the cell-descriptor constructors a module's
 * canvas.config.js uses to build its banks. Emitted BEFORE the config so the
 * constructors are in scope there; the engine (everything reading CONFIG)
 * is emitted after. See README.md for the config contract. */

/* Tunables a config may reassign at its top, BEFORE building banks:
 *   KIT_PARAM_MAX  — native range max for continuous params (obxd 100, 0..255 engines 255)
 *   KIT_SENS       — detents per step for continuous cells
 *   KIT_ENUM_SENS  — detents per step for enum cells (slower; they clamp, never wrap) */
let KIT_PARAM_MAX = 100;
let KIT_SENS = 2;
let KIT_ENUM_SENS = 3;

/* ---- pure input helpers (unit-tested off-device) ---- */

/* Relative-encoder sign: d2 1..63 = CW (+1), 65..127 = CCW (-1), else 0. */
function dirFromCC(d2) {
  if (d2 >= 1 && d2 <= 63) return 1;
  if (d2 >= 65 && d2 <= 127) return -1;
  return 0;
}

/* Clamp a bank index into [0, count-1]. */
function clampBank(idx, count) {
  if (idx < 0) return 0;
  if (idx > count - 1) return count - 1;
  return idx;
}

/* Encoder accumulator: count detents until |accum| reaches sens, then fire+reset.
 * A direction reversal discards the pending accumulation first (davebox feel). */
function accumStep(accum, dir, sens) {
  if ((accum > 0 && dir < 0) || (accum < 0 && dir > 0)) accum = 0;
  accum += dir;
  if (Math.abs(accum) >= sens) return { accum: 0, fire: true };
  return { accum: accum, fire: false };
}

/* Is SHIFT held? On device the shim does NOT forward CC 49 to shadow_ui in
 * chain-edit (its CC allowlist is 14/3/51/40-43/71-78/88), but it DOES sync
 * shift into SHM, and shadow_ui exposes it to this QuickJS context as
 * shadow_get_shift_held(). Poll that; fall back to CC-49 tracking (s.shift)
 * off-device (previewer/tests) — where the binding doesn't exist. */
function shiftHeld(s) {
  if (typeof shadow_get_shift_held === "function") return !!shadow_get_shift_held();
  return s.shift;
}

/* ---- mcufont: 5x5 monospace bitmap font (via the Echidna canvas, itself
 * from schwung-davebox assets/fonts/mcufont.h) ----
 * Rendered as flat 1-bit pixels via ctx.setPixel; the editor's draw()
 * overrides ctx.print/ctx.measureText with these, so all layout code renders
 * in this font. Uppercase only; 5px glyph + 1px gap = 6px advance. */
var PF_GLYPH_W = 5, PF_GLYPH_H = 5, PF_ADVANCE = 6;
var PF_FONT = {
  "A": ["01110", "10001", "11111", "10001", "10001"],
  "B": ["11110", "10001", "11110", "10001", "11110"],
  "C": ["01111", "10000", "10000", "10000", "01111"],
  "D": ["11110", "10001", "10001", "10001", "11110"],
  "E": ["11111", "10000", "11100", "10000", "11111"],
  "F": ["11111", "10000", "11100", "10000", "10000"],
  "G": ["01111", "10000", "10011", "10001", "01111"],
  "H": ["10001", "10001", "11111", "10001", "10001"],
  "I": ["11111", "00100", "00100", "00100", "11111"],
  "J": ["11111", "00010", "00010", "10010", "01100"],
  "K": ["10010", "10100", "11000", "10100", "10010"],
  "L": ["10000", "10000", "10000", "10000", "11111"],
  "M": ["11111", "10101", "10101", "10001", "10001"],
  "N": ["10001", "11001", "10101", "10011", "10001"],
  "O": ["01110", "10001", "10001", "10001", "01110"],
  "P": ["11110", "10001", "11110", "10000", "10000"],
  "Q": ["01110", "10001", "10001", "10010", "01101"],
  "R": ["11110", "10001", "11110", "10010", "10001"],
  "S": ["01111", "10000", "01110", "00001", "11110"],
  "T": ["11111", "00100", "00100", "00100", "00100"],
  "U": ["10001", "10001", "10001", "10001", "01110"],
  "V": ["10001", "10001", "01010", "01010", "00100"],
  "W": ["10001", "10001", "10101", "10101", "11011"],
  "X": ["10001", "01010", "00100", "01010", "10001"],
  "Y": ["10001", "01010", "00100", "00100", "00100"],
  "Z": ["11111", "00010", "00100", "01000", "11111"],
  "0": ["01110", "10001", "10101", "10001", "01110"],
  "1": ["01100", "10100", "00100", "00100", "11111"],
  "2": ["01110", "10001", "00110", "01000", "11111"],
  "3": ["11111", "00001", "01110", "00001", "11110"],
  "4": ["10010", "10010", "11111", "00010", "00010"],
  "5": ["11111", "10000", "01110", "00001", "11110"],
  "6": ["01110", "10000", "11110", "10001", "01110"],
  "7": ["11111", "00010", "00100", "01000", "01000"],
  "8": ["01110", "10001", "01110", "10001", "01110"],
  "9": ["11111", "10001", "11111", "00001", "00001"],
  " ": ["00000", "00000", "00000", "00000", "00000"],
  "-": ["00000", "00000", "01110", "00000", "00000"],
  "+": ["00000", "00100", "01110", "00100", "00000"],
  ".": ["00000", "00000", "00000", "00000", "01000"],
  ":": ["00000", "01000", "00000", "01000", "00000"],
  "/": ["00001", "00010", "00100", "01000", "10000"],
  ">": ["10000", "01000", "00100", "01000", "10000"]
};

/* Width in px of `text` in the pixel-font (no trailing gap). */
function pfWidth(text) {
  return Math.max(0, String(text).length * PF_ADVANCE - 1);
}

/* Draw `text` at (x,y) top-left in `color` (0/1) by plotting each on-pixel via
 * ctx.setPixel — the ctx.print replacement. Uppercased; missing chars -> space. */
function pfPrint(ctx, x, y, text, color) {
  var s = String(text).toUpperCase();
  var v = color ? 1 : 0;
  var ox0 = Math.round(x), oy = Math.round(y);
  for (var i = 0; i < s.length; i++) {
    var rows = PF_FONT[s[i]] || PF_FONT[" "];
    var ox = ox0 + i * PF_ADVANCE;
    for (var r = 0; r < PF_GLYPH_H; r++) {
      var row = rows[r];
      for (var c = 0; c < PF_GLYPH_W; c++) {
        if (row[c] === "1") ctx.setPixel(ox + c, oy + r, v);
      }
    }
  }
}

/* ---- header font: Not Jam Chunky Sans 6 (CC0, by Not Jam) — a chunky
 * 6px proportional pixel font with real mixed case, rasterized from the
 * TTF at native size. Glyph format: [advance, ...6 rowBits] (advance
 * already includes the font's 1px spacing), bit0 = leftmost; [n] alone =
 * blank glyph. ASCII 32-126. Used by drawChrome for the header text. ---- */
var NJ_G = [
  [5], [3,3,3,3,0,3,0], [4,5,5,0,0,0,0], [8,54,127,54,127,54,0], [6,4,30,7,28,15,4], [5,13,12,6,3,11,0], [8,14,3,126,51,30,0], [2,1,1,0,0,0,0],
  [4,6,3,3,3,6,0], [4,3,6,6,6,3,0], [4,2,7,2,0,0,0], [7,12,12,63,12,12,0], [3,0,0,0,3,3,2], [4,0,0,7,0,0,0], [3,0,0,0,3,3,0], [5,12,12,6,3,3,0],
  [6,14,27,27,27,14,0], [4,7,6,6,6,6,0], [5,7,12,6,3,15,0], [5,15,12,6,12,15,0], [6,27,27,31,24,24,0], [5,15,3,15,12,7,0], [6,12,6,31,27,14,0], [5,15,12,6,3,3,0],
  [6,14,27,14,27,14,0], [6,14,27,31,12,6,0], [3,3,3,0,3,3,0], [3,3,3,0,3,3,2], [5,12,6,3,6,12,0], [4,0,7,0,7,0,0], [5,3,6,12,6,3,0], [6,14,27,24,0,4,0],
  [8,62,99,107,51,6,28], [6,14,27,31,27,27,0], [6,15,27,15,27,15,0], [5,14,3,3,3,14,0], [6,15,27,27,27,15,0], [5,15,3,7,3,15,0], [5,15,3,7,3,3,0], [6,14,3,3,27,14,0],
  [6,27,27,31,27,27,0], [5,15,6,6,6,15,0], [4,7,6,6,6,3,0], [7,51,27,15,27,51,0], [5,3,3,3,3,15,0], [8,99,119,127,107,99,0], [7,51,55,63,59,51,0], [7,30,51,51,51,30,0],
  [6,15,27,27,15,3,0], [6,14,27,27,27,14,24], [6,15,27,27,15,27,0], [5,14,3,15,12,7,0], [5,15,6,6,6,6,0], [6,27,27,27,27,14,0], [8,99,99,54,54,28,0], [8,99,107,127,119,34,0],
  [7,51,30,12,30,51,0], [7,51,51,30,12,12,0], [5,15,12,6,3,15,0], [4,7,3,3,3,7,0], [5,3,3,6,12,12,0], [4,7,6,6,6,7,0], [4,2,7,0,0,0,0], [5,0,0,0,0,15,0],
  [3,3,3,2,0,0,0], [7,0,14,27,27,54,0], [6,3,15,27,27,15,0], [5,0,14,3,3,14,0], [6,24,30,27,27,30,0], [6,0,30,27,15,30,0], [4,6,3,7,3,3,0], [6,0,30,27,27,28,14],
  [6,3,15,27,27,27,0], [3,3,0,3,3,3,0], [4,6,0,6,6,6,3], [6,3,27,15,31,27,0], [4,3,3,3,3,6,0], [8,0,62,107,99,99,0], [6,0,14,27,27,27,0], [6,0,14,27,27,14,0],
  [6,0,14,27,27,15,3], [6,0,30,27,27,30,24], [5,0,14,3,3,3,0], [5,0,14,3,12,7,0], [4,3,7,3,3,6,0], [6,0,27,27,27,14,0], [7,0,51,51,30,12,0], [8,0,99,99,107,62,0],
  [6,0,27,14,14,27,0], [6,0,27,27,27,30,24], [5,0,15,12,6,15,0], [5,14,6,7,6,14,0], [3,3,3,3,3,3,3], [5,7,6,14,6,7,0], [9,0,14,219,112,0,0]
];

function njGlyph(cp) { return (cp < 0x20 || cp > 0x7E) ? null : NJ_G[cp - 0x20]; }

/* Width of `text` in the header font (advances include spacing; drop the
 * trailing 1px). */
function njWidth(text) {
  var s = String(text), w = 0;
  for (var i = 0; i < s.length; i++) {
    var g = njGlyph(s.charCodeAt(i));
    w += g ? g[0] : 5;
  }
  return Math.max(0, w - 1);
}

function njPrint(ctx, x, y, text, color) {
  var s = String(text), cx = Math.round(x), oy = Math.round(y);
  var v = color ? 1 : 0;
  for (var i = 0; i < s.length; i++) {
    var g = njGlyph(s.charCodeAt(i));
    if (!g) { cx += 5; continue; }
    for (var r = 0; r < 6; r++) {
      var bits = g[1 + r] || 0;
      for (var c = 0; c < 15; c++) if (bits & (1 << c)) ctx.setPixel(cx + c, oy + r, v);
    }
    cx += g[0];
  }
}

/* ---- movy main font (proportional, 5px tall; ported from schwung-movy
 * src/font/glyphs.ts + blit.ts, MIT, (c) 2026 megadake) — used for the
 * param LABEL strips (and their touched-value swap), the movy look.
 * Glyph format: [advance, yOff, w, h, ...rowBits], bit0 = leftmost pixel;
 * inter-glyph gap is -1 (glyphs tuck together). ASCII 0x20-0x7E; movy's
 * lowercase shares the uppercase shapes. ---- */
var MV_G = [
  [6, 0, 0, 0],                                  // ' '
  [3, 0, 3, 5, 2, 2, 2, 0, 2],                   // '!'
  [5, 0, 5, 2, 10, 10],                          // '"'
  [7, 0, 7, 5, 20, 62, 20, 62, 20],              // '#'
  [7, 0, 7, 5, 60, 10, 28, 40, 30],              // '$'
  [5, 0, 5, 5, 10, 8, 4, 2, 10],                 // '%'
  [5, 0, 5, 5, 4, 10, 4, 10, 12],                // '&'
  [3, 0, 3, 2, 2, 2],                            // "'"
  [4, 0, 4, 5, 4, 2, 2, 2, 4],                   // '('
  [4, 0, 4, 5, 2, 4, 4, 4, 2],                   // ')'
  [5, 1, 5, 3, 10, 4, 10],                       // '*'
  [5, 2, 5, 3, 4, 14, 4],                        // '+'
  [4, 4, 4, 3, 6, 4, 2],                         // ','
  [5, 3, 5, 1, 14],                              // '-'
  [3, 4, 3, 1, 2],                               // '.'
  [5, 0, 5, 5, 8, 8, 4, 2, 2],                   // '/'
  [6, 0, 6, 5, 30, 18, 18, 18, 30],              // '0'
  [5, 0, 5, 5, 6, 4, 4, 4, 14],                  // '1'
  [6, 0, 6, 5, 30, 16, 30, 2, 30],               // '2'
  [6, 0, 6, 5, 30, 16, 28, 16, 30],              // '3'
  [6, 0, 6, 5, 18, 18, 30, 16, 16],              // '4'
  [6, 0, 6, 5, 30, 2, 30, 16, 30],               // '5'
  [6, 0, 6, 5, 30, 2, 30, 18, 30],               // '6'
  [6, 0, 6, 5, 30, 16, 8, 4, 4],                 // '7'
  [6, 0, 6, 5, 30, 18, 30, 18, 30],              // '8'
  [6, 0, 6, 5, 30, 18, 30, 16, 30],              // '9'
  [4, 1, 4, 3, 4, 0, 4],                         // ':'
  [4, 1, 4, 4, 4, 0, 4, 2],                      // ';'
  [5, 0, 5, 5, 8, 4, 2, 4, 8],                   // '<'
  [5, 2, 5, 3, 14, 0, 14],                       // '='
  [5, 0, 5, 5, 2, 4, 8, 4, 2],                   // '>'
  [5, -1, 5, 6, 6, 8, 4, 4, 0, 4],               // '?'
  [7, 0, 7, 5, 28, 32, 44, 42, 28],              // '@'
  [6, 0, 6, 5, 12, 18, 30, 18, 18],              // 'A'
  [6, 0, 6, 5, 14, 18, 14, 18, 14],              // 'B'
  [6, 0, 6, 5, 12, 18, 2, 18, 12],               // 'C'
  [6, 0, 6, 5, 14, 18, 18, 18, 14],              // 'D'
  [6, 0, 6, 5, 30, 2, 14, 2, 30],                // 'E'
  [6, 0, 6, 5, 30, 2, 14, 2, 2],                 // 'F'
  [6, 0, 6, 5, 12, 2, 26, 18, 12],               // 'G'
  [6, 0, 6, 5, 18, 18, 30, 18, 18],              // 'H'
  [3, 0, 3, 5, 2, 2, 2, 2, 2],                   // 'I'
  [5, 0, 5, 5, 8, 8, 8, 10, 6],                  // 'J'
  [5, 0, 5, 5, 10, 10, 6, 10, 10],               // 'K'
  [6, 0, 6, 5, 2, 2, 2, 2, 30],                  // 'L'
  [7, 0, 7, 5, 30, 42, 42, 34, 34],              // 'M'
  [6, 0, 6, 5, 12, 18, 18, 18, 18],              // 'N'
  [6, 0, 6, 5, 12, 18, 18, 18, 12],              // 'O'
  [6, 0, 6, 5, 14, 18, 18, 14, 2],               // 'P'
  [6, 0, 6, 5, 12, 18, 18, 26, 28],              // 'Q'
  [6, 0, 6, 5, 14, 18, 18, 14, 18],              // 'R'
  [6, 0, 6, 5, 28, 2, 12, 16, 14],               // 'S'
  [5, 0, 5, 5, 14, 4, 4, 4, 4],                  // 'T'
  [6, 0, 6, 5, 18, 18, 18, 18, 12],              // 'U'
  [6, 0, 6, 5, 18, 18, 18, 10, 6],               // 'V'
  [7, 0, 7, 5, 34, 34, 42, 42, 30],              // 'W'
  [5, 0, 5, 5, 10, 10, 4, 10, 10],               // 'X'
  [6, 0, 6, 5, 18, 18, 28, 16, 14],              // 'Y'
  [6, 0, 6, 5, 30, 16, 12, 2, 30],               // 'Z'
  [4, 0, 4, 5, 6, 2, 2, 2, 6],                   // '['
  [5, 0, 5, 5, 2, 2, 4, 8, 8],                   // '\\'
  [4, 0, 4, 5, 6, 4, 4, 4, 6],                   // ']'
  [5, 0, 5, 2, 4, 10],                           // '^'
  [6, 5, 6, 1, 30],                              // '_'
  [4, 0, 4, 2, 2, 4],                            // '`'
  [6, 0, 6, 5, 12, 18, 30, 18, 18],              // 'a'
  [6, 0, 6, 5, 14, 18, 14, 18, 14],              // 'b'
  [6, 0, 6, 5, 12, 18, 2, 18, 12],               // 'c'
  [6, 0, 6, 5, 14, 18, 18, 18, 14],              // 'd'
  [6, 0, 6, 5, 30, 2, 14, 2, 30],                // 'e'
  [6, 0, 6, 5, 30, 2, 14, 2, 2],                 // 'f'
  [6, 0, 6, 5, 12, 2, 26, 18, 12],               // 'g'
  [6, 0, 6, 5, 18, 18, 30, 18, 18],              // 'h'
  [3, 0, 3, 5, 2, 2, 2, 2, 2],                   // 'i'
  [5, 0, 5, 5, 8, 8, 8, 10, 6],                  // 'j'
  [5, 0, 5, 5, 10, 10, 6, 10, 10],               // 'k'
  [6, 0, 6, 5, 2, 2, 2, 2, 30],                  // 'l'
  [7, 0, 7, 5, 30, 42, 42, 34, 34],              // 'm'
  [6, 0, 6, 5, 12, 18, 18, 18, 18],              // 'n'
  [6, 0, 6, 5, 12, 18, 18, 18, 12],              // 'o'
  [6, 0, 6, 5, 14, 18, 18, 14, 2],               // 'p'
  [6, 0, 6, 5, 12, 18, 18, 26, 28],              // 'q'
  [6, 0, 6, 5, 14, 18, 18, 14, 18],              // 'r'
  [6, 0, 6, 5, 28, 2, 12, 16, 14],               // 's'
  [5, 0, 5, 5, 14, 4, 4, 4, 4],                  // 't'
  [6, 0, 6, 5, 18, 18, 18, 18, 12],              // 'u'
  [6, 0, 6, 5, 18, 18, 18, 10, 6],               // 'v'
  [7, 0, 7, 5, 34, 34, 42, 42, 30],              // 'w'
  [5, 0, 5, 5, 10, 10, 4, 10, 10],               // 'x'
  [6, 0, 6, 5, 18, 18, 28, 16, 30],              // 'y'
  [6, 0, 6, 5, 30, 16, 12, 2, 30],               // 'z'
  [5, 0, 5, 5, 12, 4, 2, 4, 12],                 // '{'
  [3, 0, 3, 5, 2, 2, 2, 2, 2],                   // '|'
  [5, 0, 5, 5, 6, 4, 8, 4, 6],                   // '}'
  [6, 0, 6, 2, 20, 10]                           // '~'
];

function mvGlyph(cp) { return (cp < 0x20 || cp > 0x7E) ? null : MV_G[cp - 0x20]; }

/* Width of `text` in the movy font (advance sum, -1px inter-glyph gap). */
function mvWidth(text) {
  var s = String(text), w = 0;
  for (var i = 0; i < s.length; i++) {
    var g = mvGlyph(s.charCodeAt(i));
    w += g ? g[0] : 5;
    if (i < s.length - 1) w -= 1;
  }
  return w;
}

function mvPrint(ctx, x, y, text, color) {
  var s = String(text), cx = Math.round(x), oy = Math.round(y);
  var v = color ? 1 : 0;
  for (var i = 0; i < s.length; i++) {
    var g = mvGlyph(s.charCodeAt(i));
    if (!g) { cx += 5; continue; }
    var yOff = g[1], w = g[2], h = g[3];
    for (var r = 0; r < h; r++) {
      var bits = g[4 + r];
      for (var c = 0; c < w; c++) if (bits & (1 << c)) ctx.setPixel(cx + c, oy + yOff + r, v);
    }
    cx += g[0];
    if (i < s.length - 1) cx -= 1;
  }
}

/* ---- 5x3 micro font (ported from schwung-movy src/font/glyphs5x3.ts, MIT,
 * (c) 2026 megadake) — used INSIDE the widget boxes (enum squares, value
 * squares), where the 6px-advance 5x5 font can't fit. Glyph format:
 * [advance, yOff, w, h, ...rowBits], bit0 = leftmost pixel. ---- */
var PF3_CHARS = " !\"'()+,-./:0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ%<>=?*";
var PF3_G = [
  [4,0,0,0],
  [4,0,3,5,1,1,1,0,1], [4,0,3,5,5,5,0,0,0], [4,0,3,5,2,2,0,0,0],
  [4,0,3,5,2,1,1,1,2], [4,0,3,5,1,2,2,2,1], [4,0,3,5,2,7,2,0,0],
  [4,0,3,5,0,0,3,3,2], [4,0,3,5,0,0,7,0,0], [4,0,3,5,0,0,0,3,3],
  [4,0,3,5,4,4,2,1,1], [4,0,3,5,3,3,0,3,3],
  [4,0,3,5,7,5,5,5,7], [4,0,3,5,2,3,2,2,7], [4,0,3,5,7,4,7,1,7],
  [4,0,3,5,7,4,6,4,7], [4,0,3,5,5,5,7,4,4], [4,0,3,5,7,1,7,4,7],
  [4,0,3,5,7,1,7,5,7], [4,0,3,5,7,4,4,4,4], [4,0,3,5,7,5,7,5,7],
  [4,0,3,5,7,5,7,4,7],
  [4,0,3,5,2,7,5,5,5], [4,0,3,5,7,5,3,5,7], [4,0,3,5,7,1,1,1,7],
  [4,0,3,5,3,5,5,5,3], [4,0,3,5,7,1,3,1,7], [4,0,3,5,7,1,3,1,1],
  [4,0,3,5,7,1,5,5,7], [4,0,3,5,5,5,7,5,5], [4,0,3,5,7,2,2,2,7],
  [4,0,3,5,4,4,4,5,7], [4,0,3,5,5,5,3,5,5], [4,0,3,5,1,1,1,1,7],
  [4,0,3,5,5,7,5,5,5], [4,0,3,5,5,3,5,5,5], [4,0,3,5,7,5,5,5,7],
  [4,0,3,5,7,5,7,1,1], [4,0,3,5,3,5,5,7,2], [4,0,3,5,7,5,3,5,5],
  [4,0,3,5,6,1,2,4,3], [4,0,3,5,7,2,2,2,2], [4,0,3,5,5,5,5,5,7],
  [4,0,3,5,5,5,5,5,2], [4,0,3,5,5,5,5,7,7], [4,0,3,5,5,5,2,5,5],
  [4,0,3,5,5,5,7,2,2], [4,0,3,5,7,4,2,1,7],
  [4,0,3,5,5,4,2,1,5], [4,0,3,5,4,2,1,2,4], [4,0,3,5,1,2,4,2,1],
  [4,0,3,5,7,0,7,0,0], [4,0,3,5,7,4,6,0,2], [4,0,3,5,2,7,2,5,0]
];

function pf3Glyph(ch) {
  var i = PF3_CHARS.indexOf(ch);
  return i >= 0 ? PF3_G[i] : null;
}
function pf3Width(text) {
  var s = String(text).toUpperCase(), w = 0;
  for (var i = 0; i < s.length; i++) { var g = pf3Glyph(s[i]); w += g ? g[0] : 4; }
  return w;
}
function pf3Print(ctx, x, y, text, color) {
  var s = String(text).toUpperCase(), cx = Math.round(x), oy = Math.round(y);
  var v = color ? 1 : 0;
  for (var i = 0; i < s.length; i++) {
    var g = pf3Glyph(s[i]);
    if (!g) { cx += 4; continue; }
    var yOff = g[1], w = g[2], h = g[3];
    for (var r = 0; r < h; r++) {
      var bits = g[4 + r];
      for (var c = 0; c < w; c++) if (bits & (1 << c)) ctx.setPixel(cx + c, oy + yOff + r, v);
    }
    cx += g[0];
  }
}

/* Split an enum value into two <=3-char lines for the enum square (movy's
 * enumSquareLines): word-split when possible, else a hard split. Configs can
 * sidestep bad auto-splits ("KEE/P") with per-option `sq` labels (enumc). */
function enumSquareLines(value) {
  var parts = String(value).toUpperCase().replace(/[_\-]/g, " ").trim().split(/\s+/);
  if (parts.length >= 2) return [parts[0].substring(0, 3), parts[1].substring(0, 3)];
  var w = parts[0];
  return [w.substring(0, 3), w.substring(3, 6)];
}

/* ---- cell descriptor constructors (native-int chain contract) ----
 * The config builds its banks from these. Continuous kinds step every
 * KIT_SENS detents; enum cells step every KIT_ENUM_SENS detents and CLAMP at
 * their ends rather than wrapping — an accidental extra detent shouldn't
 * flip On back to Off. All read KIT_PARAM_MAX at call time, so a config that
 * reassigns it must do so BEFORE building its banks. */

const kToggleLabels = ["Off", "On"];

/* Continuous 0..KIT_PARAM_MAX, rendered as an arc knob. */
function uni(key, label) { return { key, label, kind: "unipolar", min: 0, max: KIT_PARAM_MAX, step: 1, sens: KIT_SENS }; }
/* Center-detent continuous (pan, tune): arc knob with a 12-o'clock tick;
 * value shows signed offset from center; center-out bar semantics. */
function bip(key, label) { return { key, label, kind: "bipolar", min: 0, max: KIT_PARAM_MAX, step: 1, sens: KIT_SENS, dflt: Math.round(KIT_PARAM_MAX / 2) }; }
/* On/Off toggle, rendered as a movy horizontal bar. */
function tog(key, label) { return { key, label, kind: "enum", min: 0, max: 1, step: 1, sens: KIT_ENUM_SENS, options: kToggleLabels }; }
/* Multi-option enum, rendered as a framed square + a scrolling list overlay
 * while touched. `sq` (optional): per-option single-line square labels. */
function enumc(key, label, options, sq) { return { key, label, kind: "enum", min: 0, max: options.length - 1, step: 1, sens: KIT_ENUM_SENS, options, sq }; }
/* Small signed range (+N display), rendered as a value square. */
function oct(key, label, lo, hi) { return { key, label, kind: "octave", min: lo, max: hi, step: 1, sens: 3 }; }
/* Small positive count, rendered as a value square. */
function count(key, label, lo, hi) { return { key, label, kind: "count", min: lo, max: hi, step: 1, sens: 3 }; }
/* Envelope-stage cell (use on `env: true` banks, cells 0-3 = A/D/S/R drive
 * the full-width envelope graphic; other fader cells render as a vbar). */
function fader(key, label) { return { key, label, kind: "fader", min: 0, max: KIT_PARAM_MAX, step: 1, sens: KIT_SENS }; }
/* Empty grid slot (keeps knob positions aligned in dynamicCells layouts). */
function blank() { return { key: null, label: "", kind: "blank" }; }
/* Waveform-shape enum: like enumc, but the widget draws the selected shape's
 * actual waveform (shapeSample) instead of its name. `shapes` = one shape id
 * per option: "sine" | "tri" | "saw" | "square" | "sh" | "swishy". */
function wavesel(key, label, options, shapes) { return { key, label, kind: "waveenum", min: 0, max: options.length - 1, step: 1, sens: KIT_ENUM_SENS, options, shapes }; }

/* Bipolar (-1..1) sample of an LFO shape at phase t (one cycle = 1). s&h and
 * swishy use fixed deterministic patterns so frames are stable (from
 * schwung-movy src/renderer/lfo-wave.ts, MIT (c) 2026 megadake). */
function shapeSample(shape, t) {
  var ph = t - Math.floor(t);
  switch (shape) {
    case "tri":
      if (ph < 0.25) return ph * 4;
      if (ph < 0.75) return 1 - (ph - 0.25) * 4;
      return -1 + (ph - 0.75) * 4;
    case "saw": return ph * 2 - 1;
    case "square": return ph < 0.5 ? 1 : -1;
    case "sh": {
      var steps = [0.3, -0.7, 0.85, -0.35];
      return steps[Math.floor(ph * steps.length) % steps.length];
    }
    case "swishy": {
      var pts = [0, 0.7, -0.4, 0.55, -0.8, 0.2, 0];
      var x = ph * (pts.length - 1);
      var i = Math.floor(x), f = x - i;
      return pts[i] + (pts[Math.min(i + 1, pts.length - 1)] - pts[i]) * f;
    }
    default: return Math.sin(ph * 2 * Math.PI); // sine
  }
}

/* Swappable clock for the step-editor playhead: prefer a host tempo clock
 * when present, else wall time. */
function nowMs() { return (typeof host_now_ms === "function") ? host_now_ms() : Date.now(); }


/* ==== module config (canvas.config.js) ==== */

/* PALETTE canvas config for schwung-canvaskit (../../schwung-canvaskit).
 * This is the SOURCE for src/canvas.js — regenerate after editing:
 *   node ../schwung-canvaskit/build.mjs src/canvas.config.js src/canvas.js
 * Concatenated between the kit prelude (cell constructors in scope) and the
 * kit engine (which reads CONFIG) inside one IIFE.
 *
 * Wire contract (src/dsp/mod.h + src/dsp/palette.c set_param/get_param):
 * floats are 0..1 strings ("0.6300"; input_vol 0..2), enums exchange DISPLAY
 * values — the option LABEL on read, the option INDEX on write (the DSP's
 * pm_enum_from_str/pm_dest_from_str/fxN_select resolve digit-first). The kit
 * cells work in a native-int domain (0..100), so every cell carries a
 * parse/format codec pair. */

KIT_PARAM_MAX = 100;
/* Slower enum stepping (kit default 3): palette's lists are long (25 FX,
 * 22 dests, 24 reorders). 5 matched the hand-written canvas; Josh wanted
 * it slower still on device -> 7. */
KIT_ENUM_SENS = 7;

/* ---- enum label tables (must match the engine's get_param output EXACTLY —
 * see src/dsp/mod.h PM_MODE_NAMES/PM_SYNC_NAMES/PM_WAVE_NAMES/pm_dest_label,
 * and palette.c FX_NAMES / DIVS[] / tempo_src / fx_reorder PERM[]). ---- */

/* FX select list — 25 entries, index 0 = "Off" (palette.c FX_NAMES[PFX_COUNT]). */
const FX_NAMES = ["Off", "Drive", "Sweeten", "Fuzz", "Howl", "Fold", "Swell",
                  "Doubler", "Vibrato", "Phaser", "Tremolo", "Pitch", "Shift",
                  "Cascade", "Reels", "Collage", "Reverse", "Space", "Bloom",
                  "Filter", "Squash", "Cassette", "Broken", "Interference", "Halo"];

/* Destination labels 0..21 (mod.h PM_NDEST=22 / pm_dest_label). */
const DEST_LABELS = ["None", "FX1 Amount", "FX1 Macro", "FX1 Drift",
                     "FX2 Amount", "FX2 Macro", "FX2 Drift",
                     "FX3 Amount", "FX3 Macro", "FX3 Drift",
                     "FX4 Amount", "FX4 Macro", "FX4 Drift",
                     "Mix", "Feedback", "Input Vol",
                     "Mod 1 Rate", "Mod 2 Rate", "Mod 3 Rate",
                     "Mod 1 Level", "Mod 2 Level", "Mod 3 Level"];
const DEST_SQ = ["OFF", "F1A", "F1M", "F1D", "F2A", "F2M", "F2D",
                 "F3A", "F3M", "F3D", "F4A", "F4M", "F4D",
                 "MIX", "FB", "IN", "M1R", "M2R", "M3R", "M1L", "M2L", "M3L"];

const MODE_LABELS     = ["LFO", "Envelope", "Random"];             /* m{n}_mode */
const MODE_SQ         = ["LFO", "ENV", "RND"];
const MODSYNC_LABELS  = ["Free", "Key", "BPM", "BPM+Key"];         /* m{n}_sync */
const MODSYNC_SQ      = ["FRE", "KEY", "BPM", "B+K"];
const LFOWAVE_LABELS  = ["Triangle", "Square", "Pulse 25", "Trapezoid", "Chaos", "Saw Down"]; /* m{n}_lfo_wave */
const LFOWAVE_SQ      = ["TRI", "SQR", "P25", "TRP", "CHA", "SAW"];
const TEMPOSRC_LABELS = ["Move", "Int"];                           /* tempo_src */
const TIMEDIV_LABELS  = ["Free", "1/1", "1/2", "1/2T", "1/2D", "1/4", "1/4T", "1/4D",
                         "1/8", "1/8T", "1/8D", "1/16", "1/16T", "1/16D", "1/32"]; /* time_div */
const TIMEDIV_SQ      = ["FRE", "1/1", "1/2", "2T", "2D", "1/4", "4T", "4D",
                         "1/8", "8T", "8D", "16", "16T", "16D", "32"];

/* FX reorder — 24 permutations of [1,2,3,4] in lexicographic order, "N-N-N-N"
 * strings. Matches palette.c PERM[24][4] (0-based lex order + 1). Generated
 * here rather than hand-listed so the order can't drift from the algorithm. */
const FX_REORDER_LABELS = (function () {
  function permsOf(arr) {
    if (arr.length <= 1) return [arr];
    const out = [];
    for (let i = 0; i < arr.length; i++) {
      const rest = arr.slice(0, i).concat(arr.slice(i + 1));
      const subs = permsOf(rest);
      for (let j = 0; j < subs.length; j++) out.push([arr[i]].concat(subs[j]));
    }
    return out;
  }
  const all = permsOf([1, 2, 3, 4]);
  all.sort((a, b) => {
    for (let i = 0; i < 4; i++) if (a[i] !== b[i]) return a[i] - b[i];
    return 0;
  });
  return all.map((p) => p.join("-"));
})();

/* ---- wire codecs over the kit constructors ---- */

/* Float 0..1 wire ("0.6300") <-> 0..100 int domain. */
function fcodec(cell) {
  cell.parse = (raw) => Math.round(parseFloat(raw) * 100);
  cell.format = (v) => String(+(v / 100).toFixed(4));
  return cell;
}
function funi(key, label, name) { const c = fcodec(uni(key, label)); c.name = name; return c; }
/* Bipolar float (levels, center 0.5): display as a signed percent (+-100). */
function fbip(key, label, name) {
  const c = fcodec(bip(key, label));
  c.name = name;
  c.text = (ctx) => {
    const sgn = (getRaw(ctx, c) - 50) * 2;
    return (sgn > 0 ? "+" : "") + sgn;
  };
  return c;
}
/* input_vol: float 0..2 wire, unity 1 -> 0..200 int, "1.00" readout. */
function fvol(key, label, name) {
  const c = uni(key, label);
  c.name = name;
  c.max = 200; c.dflt = 100;
  c.parse = (raw) => Math.round(parseFloat(raw) * 100);
  c.format = (v) => String(+(v / 100).toFixed(2));
  c.text = (ctx) => (getRaw(ctx, c) / 100).toFixed(2);
  return c;
}
/* Label-wire enum: get_param returns the option LABEL; writes stay the
 * index (the DSP resolves digit-first). Cached self-writes parse as digits. */
function lenum(key, label, options, sq, name) {
  const c = enumc(key, label, options, sq);
  c.name = name;
  c.parse = (raw) => {
    const i = options.indexOf(String(raw));
    if (i >= 0) return i;
    const n = parseInt(raw, 10);
    return isNaN(n) ? 0 : n;
  };
  return c;
}
function destc(key, label, name) { return lenum(key, label, DEST_LABELS, DEST_SQ, name); }
/* Macros bank route cursor: a LOCAL UI cell (no engine param) picking which
 * macro's dest/level knobs 5-6 edit. Lives in ctx.state.macroSel. */
function routec(label) {
  return { key: null, label, name: "Edit Route (M1-M4)", kind: "count", min: 1, max: 4, step: 1, sens: KIT_SENS,
    get: (ctx) => (ctx.state.macroSel || 1),
    set: (ctx, v) => { ctx.state.macroSel = v; } };
}
/* current_preset: get_param returns "N Name"; write the leading int +-1
 * (the DSP clamps 1..25 and loads the preset -> full cache flush below). */
function presetc(key, label) {
  const c = count(key, label, 1, 25);
  c.name = "Preset";
  c.get = (ctx) => { const n = parseInt(ctx.getParam(key), 10); return isNaN(n) ? 1 : n; };
  c.set = (ctx, v) => ctx.setParam(key, String(v));
  c.text = (ctx) => String(ctx.getParam(key) || "1 Init");
  c.sqText = (ctx) => String(c.get(ctx));
  return c;
}

/* ---- bank builders ---- */

function fxBank(n) {
  const pfx = "fx" + n + "_";
  return {
    label: "FX " + n,
    knobs: [lenum(pfx + "select", "Sel", FX_NAMES, null, "FX " + n + " Select"),
            funi(pfx + "amount", "Amt", "FX " + n + " Amount"),
            funi(pfx + "macro", "Mcro", "FX " + n + " Macro"),
            funi(pfx + "drift", "Drft", "FX " + n + " Drift")],
    header: (ctx) => "FX " + n + ": " + (ctx.getParam(pfx + "select") || "Off")
  };
}

/* Mode-dependent shape cells (knobs 3-5), re-resolved each render. */
function modShape(mode, pfx, mn) {
  if (mode === 1) return [funi(pfx + "env_a", "Atk", mn + " Env Attack"),
                          funi(pfx + "env_dr", "D-R", mn + " Env Dec/Rel"),
                          funi(pfx + "env_s", "Sus", mn + " Env Sustain")];
  if (mode === 2) return [funi(pfx + "rnd_rate", "Rate", mn + " Rnd Rate"),
                          funi(pfx + "rnd_lag", "Lag", mn + " Rnd Lag"),
                          funi(pfx + "rnd_prob", "Prob", mn + " Rnd Prob")];
  return [funi(pfx + "lfo_rate", "Rate", mn + " LFO Rate"),
          lenum(pfx + "lfo_wave", "Wave", LFOWAVE_LABELS, LFOWAVE_SQ, mn + " LFO Wave"),
          funi(pfx + "lfo_fade", "Fade", mn + " LFO Fade")];
}
function modIndex(ctx, key) {
  const raw = ctx.getParam(key);
  const i = MODE_LABELS.indexOf(String(raw));
  if (i >= 0) return i;
  const n = parseInt(raw, 10);
  return isNaN(n) ? 0 : n;
}
function modBank(n) {
  const pfx = "m" + n + "_", mn = "Mod " + n;
  const cellsAt = (mode) => [
    lenum(pfx + "mode", "Mode", MODE_LABELS, MODE_SQ, mn + " Mode"),
    lenum(pfx + "sync", "Sync", MODSYNC_LABELS, MODSYNC_SQ, mn + " Sync"),
    ...modShape(mode, pfx, mn),
    destc(pfx + "dest", "Dest", mn + " Dest"),
    fbip(pfx + "level", "Lvl", mn + " Level")
  ];
  return {
    label: "Mod " + n,
    knobs: cellsAt(0),                              // static fallback = LFO shape
    dynamicCells: (ctx) => cellsAt(modIndex(ctx, pfx + "mode")),
    dynamicKeys: [pfx + "env_a", pfx + "env_dr", pfx + "env_s",
                  pfx + "rnd_rate", pfx + "rnd_lag", pfx + "rnd_prob"],
    header: (ctx) => "Mod " + n + ": " + MODE_LABELS[modIndex(ctx, pfx + "mode")]
  };
}

/* Macros: 4 macro values, the route cursor, then DEST+LEVEL for the cursored
 * macro. macro{n}_dest/level ARE independently addressable per macro in the
 * DSP; the cursor is purely this UI's way of picking which one knobs 6-7 edit. */
const macroBank = {
  label: "Macros",
  knobs: [funi("macro1", "M1", "Macro 1"), funi("macro2", "M2", "Macro 2"),
          funi("macro3", "M3", "Macro 3"), funi("macro4", "M4", "Macro 4"),
          routec("Rte"), destc("macro1_dest", "Dest", "Macro 1 Dest"),
          fbip("macro1_level", "Lvl", "Macro 1 Level")],
  dynamicCells: (ctx, s) => {
    const sel = Math.max(1, Math.min(4, (s && s.macroSel) || 1));
    return [funi("macro1", "M1", "Macro 1"), funi("macro2", "M2", "Macro 2"),
            funi("macro3", "M3", "Macro 3"), funi("macro4", "M4", "Macro 4"),
            routec("Rte"), destc("macro" + sel + "_dest", "Dest", "Macro " + sel + " Dest"),
            fbip("macro" + sel + "_level", "Lvl", "Macro " + sel + " Level")];
  },
  dynamicKeys: ["macro2_dest", "macro2_level", "macro3_dest", "macro3_level",
                "macro4_dest", "macro4_level"],
  header: (ctx, s) => "Macros > M" + Math.max(1, Math.min(4, (s && s.macroSel) || 1))
};

const reorderCell = lenum("fx_reorder", "Ordr", FX_REORDER_LABELS, null, "FX Reorder");
reorderCell.sqText = (ctx) => String(FX_REORDER_LABELS[getRaw(ctx, reorderCell)] || "1-2-3-4").replace(/-/g, "");

const tempoCell = count("tempo_bpm", "Tmpo", 10, 500);
tempoCell.name = "Tempo (BPM)";

const globalBank = {
  label: "Global",
  knobs: [fvol("input_vol", "InVl", "Input Volume"), funi("mix", "Mix", "Mix"),
          funi("feedback", "Fdbk", "Feedback"),
          reorderCell,
          lenum("tempo_src", "TSrc", TEMPOSRC_LABELS, null, "Tempo Source"),
          tempoCell,
          lenum("time_div", "TDiv", TIMEDIV_LABELS, TIMEDIV_SQ, "Time Division"),
          presetc("current_preset", "Prst")]
};

const CONFIG = {
  name: "Palette",

  banks: [fxBank(1), fxBank(2), fxBank(3), fxBank(4),
          modBank(1), modBank(2), modBank(3),
          macroBank, globalBank],

  /* Picker rows 1:1 with banks (palette is flat — 9 peers, no sub-grouping). */
  sections: [
    { name: "FX 1", bank: 0 }, { name: "FX 2", bank: 1 },
    { name: "FX 3", bank: 2 }, { name: "FX 4", bank: 3 },
    { name: "MOD 1", bank: 4 }, { name: "MOD 2", bank: 5 }, { name: "MOD 3", bank: 6 },
    { name: "MACROS", bank: 7 }, { name: "GLOBAL", bank: 8 }
  ],

  icons: ["fx1", "fx2", "fx3", "fx4", "sine", "sine", "sine", "routes", "global"],
  customIcons: {
    fx1: { w: 17, draw(ctx, x, y, fg) { ctx.print(x, y + 1, "FX1", fg); } },
    fx2: { w: 17, draw(ctx, x, y, fg) { ctx.print(x, y + 1, "FX2", fg); } },
    fx3: { w: 17, draw(ctx, x, y, fg) { ctx.print(x, y + 1, "FX3", fg); } },
    fx4: { w: 17, draw(ctx, x, y, fg) { ctx.print(x, y + 1, "FX4", fg); } }
  },

  /* WIRE-format defaults (mirroring src/dsp/mod.h pm_mod_init / palette.c
   * param defaults) — only consumed off-device (previewer/tests). */
  defaults: {
    fx1_select: "Off", fx1_amount: "0", fx1_macro: "0", fx1_drift: "0",
    fx2_select: "Off", fx2_amount: "0", fx2_macro: "0", fx2_drift: "0",
    fx3_select: "Off", fx3_amount: "0", fx3_macro: "0", fx3_drift: "0",
    fx4_select: "Off", fx4_amount: "0", fx4_macro: "0", fx4_drift: "0",
    m1_mode: "LFO", m1_sync: "Free", m1_lfo_rate: "0.3", m1_lfo_wave: "Triangle", m1_lfo_fade: "0.5",
    m1_env_a: "0.1", m1_env_dr: "0.4", m1_env_s: "0.5",
    m1_rnd_rate: "0.3", m1_rnd_lag: "0.5", m1_rnd_prob: "0.5",
    m1_dest: "None", m1_level: "0.5",
    m2_mode: "LFO", m2_sync: "Free", m2_lfo_rate: "0.3", m2_lfo_wave: "Triangle", m2_lfo_fade: "0.5",
    m2_env_a: "0.1", m2_env_dr: "0.4", m2_env_s: "0.5",
    m2_rnd_rate: "0.3", m2_rnd_lag: "0.5", m2_rnd_prob: "0.5",
    m2_dest: "None", m2_level: "0.5",
    m3_mode: "LFO", m3_sync: "Free", m3_lfo_rate: "0.3", m3_lfo_wave: "Triangle", m3_lfo_fade: "0.5",
    m3_env_a: "0.1", m3_env_dr: "0.4", m3_env_s: "0.5",
    m3_rnd_rate: "0.3", m3_rnd_lag: "0.5", m3_rnd_prob: "0.5",
    m3_dest: "None", m3_level: "0.5",
    macro1: "0", macro2: "0", macro3: "0", macro4: "0",
    macro1_dest: "None", macro1_level: "0.5", macro2_dest: "None", macro2_level: "0.5",
    macro3_dest: "None", macro3_level: "0.5", macro4_dest: "None", macro4_level: "0.5",
    input_vol: "1.0", mix: "1.0", feedback: "0",
    fx_reorder: "1-2-3-4", tempo_src: "Move", tempo_bpm: "120", time_div: "Free",
    current_preset: "1 Init"
  },

  /* Post-write cache rules — palette's two engine-rewrites-the-value cases:
   * fx*_select runs the effect-uniqueness SKIP walk (the index we WROTE may
   * not be where it LANDS — caching the requested value desyncs the display
   * and the next step's "current" read -> erratic selection), and *_dest
   * moves the depth-table cell that *_level reads/writes. Preset loads
   * change everything -> full flush. */
  writeInvalidates: (key) => {
    if (key === "current_preset") return true;
    if (/_select$/.test(key)) return [key];
    if (/_dest$/.test(key)) return [key.slice(0, -5) + "_level"];
    return null;
  },

  testExports: { FX_NAMES, DEST_LABELS, MODE_LABELS, MODSYNC_LABELS, LFOWAVE_LABELS,
                 TEMPOSRC_LABELS, TIMEDIV_LABELS, FX_REORDER_LABELS, modIndex }
};


/* ==== kit engine ==== */

/* ==== schwung-canvaskit core: engine ====
 * Everything downstream of the module CONFIG: bank model aliases, state,
 * movy-style widgets (arc knobs / bar toggles / enum + value squares / ADSR
 * graphic — adapted from schwung-movy src/renderer/*.ts, MIT (c) 2026
 * megadake), header chrome + icon set, SHIFT section picker, enum overlay,
 * input handling, param cache, and the bank_editor overlay object. */

/* ---- module config aliases ---- */
const BANKS = CONFIG.banks;
const JUMP_SECTIONS = CONFIG.sections;
const BANK_ICONS = CONFIG.icons || [];
const DEFAULTS = CONFIG.defaults || {};
/* Detents per picker step while SHIFT-scrolling (1 = one section per click). */
const NAV_SENS = CONFIG.navSens || 1;

/* Which section the current bank falls under (the last target <= bankIdx). */
function activeSection(bankIdx) {
  let idx = 0;
  for (let i = 0; i < JUMP_SECTIONS.length; i++) if (JUMP_SECTIONS[i].bank <= bankIdx) idx = i;
  return idx;
}

/* ---- dynamic cells + step-editor plumbing ----
 * bank.dynamicCells(ctx) -> cells[]  — type-dependent pages (FX banks whose
 *   knobs relabel by the armed type; dest cells with live route names).
 * bank.steps = { csv, sel, lvl, count, max?, active?(ctx), stepMs?(ctx) }
 *   — an echidna-style step-sequencer editor reached by jogging RIGHT from
 *   the bank (jog LEFT backs out). Engine contract: `csv` getParam returns
 *   comma-separated levels; writes go `sel` (step index) then `lvl` (value);
 *   `count` is the step-count param key (or a number). */

function stepsMax(bank) { return (bank.steps && bank.steps.max) || KIT_PARAM_MAX; }
function stepsCenter(bank) { return Math.round(stepsMax(bank) / 2); }

function stepCount(ctx, bank) {
  const c = bank.steps.count;
  if (typeof c === "number") return c;
  const v = parseInt(ctx.getParam(c) || "8", 10);
  return isNaN(v) ? 8 : Math.max(1, Math.min(32, v));
}

function stepCells(bank, page) {
  const a = [];
  for (let k = 0; k < 8; k++) {
    a.push({ label: String(page * 8 + k + 1), kind: "steplvl", min: 0, max: stepsMax(bank), stepIdx: page * 8 + k });
  }
  return a;
}

function subPageCount(ctx, bank) {
  if (!bank.steps) return 0;
  if (bank.steps.active && !bank.steps.active(ctx)) return 0;
  return Math.ceil(stepCount(ctx, bank) / 8);
}

/* The active bank's cells for the current sub-page. dynamicCells receives
 * (ctx, s) — s for banks whose layout depends on local UI state (a route
 * cursor picking which param a cell edits); ctx-only configs ignore it. */
function cellsFor(ctx, bank, sub, s) {
  if (bank.steps && sub >= 1) return stepCells(bank, sub - 1);
  return bank.dynamicCells ? bank.dynamicCells(ctx, s) : bank.knobs;
}

/* Header text: bank.header(ctx, s) makes it live ("FX 1: Drive"). */
function headerFor(ctx, bank, s) {
  return bank.header ? String(bank.header(ctx, s)) : bank.label;
}

/* What the header bar shows this frame: normally the bank header
 * (left-aligned); while a knob is touched/turned, the touched cell's FULL
 * param name (cell.name, falling back to its short label), centered — the
 * label strip below swaps to the VALUE, so the header carries the name. */
function headerTextFor(ctx, bank, s, cells) {
  const t = s.lastKnob >= 0 && cells ? cells[s.lastKnob] : null;
  if (t && t.kind !== "blank") return { text: String(t.name || t.label), centered: true };
  return { text: headerFor(ctx, bank, s), centered: false };
}

/* Batch-read the step levels from the engine's CSV getter. One parse per
 * draw; missing engine data -> all-center so the editor draws pre-wire. */
function stepVals(ctx, bank) {
  const center = stepsCenter(bank);
  const raw = ctx.getParam(bank.steps.csv);
  const a = [];
  if (!raw) { for (let i = 0; i < 32; i++) a.push(center); return a; }
  const parts = String(raw).split(",");
  for (let i = 0; i < 32; i++) { const v = parseInt(parts[i], 10); a.push(isNaN(v) ? center : v); }
  return a;
}

/* Which step the playhead is on right now. Default 125ms/step (~120bpm
 * 1/16ths); banks can supply steps.stepMs(ctx) for the real rate. */
function stepPlayhead(ctx, bank, count) {
  const ms = bank.steps.stepMs ? bank.steps.stepMs(ctx) : 125;
  return Math.floor(nowMs() / Math.max(1, ms)) % Math.max(1, count);
}

/* ---- state / lifecycle ---- */

function readState(ctx) {
  const s = ctx.state;
  if (!s.init) {
    s.init = true;
    let v = parseInt(ctx.getValue() || "0", 10);
    if (isNaN(v)) v = 0;
    s.bank = clampBank(v, BANKS.length);
    s.accum = [0, 0, 0, 0, 0, 0, 0, 0];
    s.lastKnob = -1;
    s.shift = false;       // SHIFT fallback state (CC 49) for off-device runs
    s.jogAccum = 0;        // shift+jog detent accumulator
    s.sub = 0;             // step-editor sub-page (0 = the bank's config page)
    s.stepSelKey = null;   // step-editor cursor (bank:idx) written to the engine
    s.stepVal = 0;         // tracked value of the step being edited
  }
  return s;
}

/* ---- value formatting ---- */

/* 8 rows: 1px pad + 6px header-font glyphs + 1px pad. */
const HDR_H = 8;

/* A cell's current value in its native-int domain. Hooks (all optional):
 *   cell.get(ctx) -> int     — bypass the param system entirely (local UI
 *                              cursors reading ctx.state, computed values).
 *   cell.parse(wire) -> int  — decode a non-int wire format (float-string
 *                              engines, enums whose get_param returns the
 *                              option LABEL). NaN falls back like parseInt. */
function getRaw(ctx, cell) {
  if (cell.get) return cell.get(ctx);
  const fallback = cell.dflt != null ? cell.dflt : cell.min;
  const raw = ctx.getParam(cell.key);
  if (raw == null || raw === "") return fallback;
  const v = cell.parse ? cell.parse(String(raw)) : parseInt(raw, 10);
  return (typeof v === "number" && !isNaN(v)) ? v : fallback;
}

/* Trim text from the end until it fits maxW px (measured in the live font). */
function fitText(ctx, text, maxW) {
  if (maxW <= 0) return "";
  let t = String(text);
  while (t.length > 0 && ctx.measureText(t) > maxW) t = t.slice(0, -1);
  return t;
}

/* Resolve {text, bar/centerBar/fader} for a cell. bar/fader are null unless
 * that cell's kind uses them (each is a 0..1 fill fraction); centerBar is a
 * -1..1 signed fraction for the center-detent kinds. */
function formatCell(ctx, cell) {
  const f = formatCellBase(ctx, cell);
  // cell.text(ctx) overrides the display STRING only (bars keep kind logic):
  // raw engine strings ("1 Init" preset names), rescaled readouts ("1.00").
  if (cell.text) f.text = String(cell.text(ctx));
  return f;
}

function formatCellBase(ctx, cell) {
  const raw = getRaw(ctx, cell);
  if (cell.kind === "enum") {
    const idx = raw - cell.min;
    const name = cell.options[idx] || ("#" + raw);
    return { text: name, bar: null, fader: null };
  }
  if (cell.kind === "bipolar") {
    const center = cell.dflt != null ? cell.dflt : Math.round((cell.min + cell.max) / 2);
    const signed = raw - center;
    const halfR = Math.max(1, Math.max(cell.max - center, center - cell.min));
    return { text: (signed > 0 ? "+" : "") + signed, bar: null, fader: null, centerBar: signed / halfR };
  }
  if (cell.kind === "octave") {
    return { text: (raw > 0 ? "+" : "") + raw, bar: null, fader: null };
  }
  if (cell.kind === "count") {
    return { text: String(raw), bar: null, fader: null };
  }
  const frac = Math.max(0, Math.min(1, (raw - cell.min) / (cell.max - cell.min)));
  if (cell.kind === "fader") return { text: String(raw), bar: null, fader: frac };
  return { text: String(raw), bar: frac, fader: null }; // unipolar
}

/* ---- icon set (drawn in the picker rows; header stays label-only) ----
 * Built-ins below; a config can add its own via CONFIG.customIcons:
 *   { myicon: { w: 12, draw(ctx, x, y, fg) { ... } } }
 * and reference "myicon" in CONFIG.icons. */

const ICON_W = { sawpulse: 12, pulse: 8, lp: 11, hp: 11, envf: 17, enva: 17, env: 12, sine: 13, routes: 12, bend: 12, random: 11, pan: 13, global: 7 };

function iconW(icon) {
  const c = CONFIG.customIcons && CONFIG.customIcons[icon];
  return c ? c.w : (ICON_W[icon] || 0);
}

function plotLine(ctx, x1, y1, x2, y2, fg) {
  const dx = x2 - x1, dy = y2 - y1;
  const steps = Math.max(1, Math.round(Math.max(Math.abs(dx), Math.abs(dy))));
  for (let s = 0; s <= steps; s++) {
    const t = s / steps;
    ctx.setPixel(Math.round(x1 + dx * t), Math.round(y1 + dy * t), fg);
  }
}

function drawBankIcon(ctx, x, y, icon, fg) {
  fg = fg ? 1 : 0;
  const custom = CONFIG.customIcons && CONFIG.customIcons[icon];
  if (custom) return custom.draw(ctx, x, y, fg);
  if (icon === "sawpulse") {
    // a saw tooth next to a pulse wave
    plotLine(ctx, x, y + 6, x + 4, y, fg); plotLine(ctx, x + 4, y, x + 4, y + 6, fg);
    plotLine(ctx, x + 6, y + 6, x + 6, y, fg);
    ctx.fillRect(x + 6, y, 3, 1, fg);
    plotLine(ctx, x + 8, y, x + 8, y + 6, fg);
    ctx.fillRect(x + 8, y + 6, 3, 1, fg);
    plotLine(ctx, x + 10, y + 6, x + 10, y, fg);
  } else if (icon === "pulse") {
    // single pulse bracket (PW)
    plotLine(ctx, x, y + 6, x, y, fg);
    ctx.fillRect(x, y, 4, 1, fg);
    plotLine(ctx, x + 3, y, x + 3, y + 6, fg);
    ctx.fillRect(x + 3, y + 6, 4, 1, fg);
    plotLine(ctx, x + 6, y + 6, x + 6, y, fg);
  } else if (icon === "lp") {
    ctx.fillRect(x, y + 1, 6, 1, fg); plotLine(ctx, x + 5, y + 1, x + 10, y + 6, fg);
  } else if (icon === "hp") {
    plotLine(ctx, x, y + 6, x + 5, y + 1, fg); ctx.fillRect(x + 5, y + 1, 6, 1, fg);
  } else if (icon === "env") {
    // plain ADSR shape (no letter tag)
    plotLine(ctx, x, y + 6, x + 2, y, fg); plotLine(ctx, x + 2, y, x + 5, y + 3, fg);
    ctx.fillRect(x + 5, y + 3, 3, 1, fg); plotLine(ctx, x + 8, y + 3, x + 11, y + 6, fg);
  } else if (icon === "envf" || icon === "enva") {
    // Env banks: an A (Amp) or F (Filter) tag to the left of the ADSR shape.
    ctx.print(x - 2, y + 1, icon === "enva" ? "A" : "F", fg);
    const ex = x + 5;
    plotLine(ctx, ex, y + 6, ex + 2, y, fg); plotLine(ctx, ex + 2, y, ex + 5, y + 3, fg);
    ctx.fillRect(ex + 5, y + 3, 3, 1, fg); plotLine(ctx, ex + 8, y + 3, ex + 11, y + 6, fg);
  } else if (icon === "sine") {
    // continuous sine (LFO)
    let py = y + 3;
    for (let i = 1; i <= 12; i++) {
      const cy = y + 3 - Math.round(2.5 * Math.sin((i / 12) * Math.PI * 4));
      plotLine(ctx, x + i - 1, py, x + i, cy, fg);
      py = cy;
    }
  } else if (icon === "routes") {
    // filled right-pointing arrow (mod/LFO destinations)
    ctx.fillRect(x, y + 2, 6, 3, fg);
    for (let c = 0; c <= 6; c++) {
      const hh = 3 - Math.floor(c / 2);
      ctx.fillRect(x + 5 + c, y + 3 - hh, 1, hh * 2 + 1, fg);
    }
  } else if (icon === "bend") {
    // pitch mod: a ramp bending up with an arrowhead
    plotLine(ctx, x, y + 6, x + 8, y + 1, fg);
    plotLine(ctx, x + 5, y, x + 8, y + 1, fg);
    plotLine(ctx, x + 8, y + 1, x + 7, y + 4, fg);
  } else if (icon === "random") {
    // scattered dots (per-voice variation / drift)
    const dots = [[0, 4], [1, 2], [3, 5], [4, 1], [6, 4], [7, 2], [9, 5], [10, 3]];
    for (const [dx, dy] of dots) ctx.setPixel(x + dx, y + dy, fg);
  } else if (icon === "pan") {
    // stereo pan: center bar with arrows pointing left + right
    ctx.fillRect(x + 6, y + 1, 1, 5, fg);
    plotLine(ctx, x + 4, y + 3, x + 1, y + 3, fg);
    ctx.setPixel(x + 2, y + 2, fg); ctx.setPixel(x + 2, y + 4, fg);
    plotLine(ctx, x + 8, y + 3, x + 11, y + 3, fg);
    ctx.setPixel(x + 10, y + 2, fg); ctx.setPixel(x + 10, y + 4, fg);
  } else if (icon === "global") {
    ctx.fillRect(x + 2, y + 2, 3, 3, fg);
    ctx.setPixel(x + 3, y, fg); ctx.setPixel(x + 3, y + 6, fg); ctx.setPixel(x, y + 3, fg); ctx.setPixel(x + 6, y + 3, fg);
    ctx.setPixel(x + 1, y + 1, fg); ctx.setPixel(x + 5, y + 1, fg); ctx.setPixel(x + 1, y + 5, fg); ctx.setPixel(x + 5, y + 5, fg);
  }
}

/* Header bar: normally an INVERTED filled bar — bank label in black on
 * white, left-aligned (icons live on the picker rows) — with the page
 * indicator below it. While a knob is touched/turned (`swap`) it flips to
 * plain white-on-black with the param name centered — the state change is
 * the touch feedback. */
function fitNj(text, maxW) {
  let t = String(text);
  while (t.length > 0 && njWidth(t) > maxW) t = t.slice(0, -1);
  return t;
}

function drawChrome(ctx, headerLabel, s, swap) {
  const t = fitNj(headerLabel, ctx.width - 4);
  if (swap) {
    njPrint(ctx, Math.max(2, Math.round((ctx.width - njWidth(t)) / 2)), 1, t, 1);
  } else {
    // filled bar rows 0-7 (text 1-6)
    ctx.fillRect(0, 0, ctx.width, HDR_H, 1);
    njPrint(ctx, 2, 1, t, 0);
  }
  // Page-indicator bar on row 9 (+10 active), shown in BOTH states (movy's
  // drawBankBar): one segment per bank split by 1px dividers, the ACTIVE
  // bank's segment 2px tall.
  const barY = HDR_H + 1;
  const n = BANKS.length;
  if (n <= 1) {
    ctx.fillRect(0, barY, ctx.width, 1, 1);
  } else {
    const segW = Math.floor((ctx.width - (n - 1)) / n);
    for (let b = 0; b < n; b++) {
      const sx = b * (segW + 1);
      const sw = b === n - 1 ? ctx.width - sx : segW;
      ctx.fillRect(sx, barY, sw, b === s.bank ? 2 : 1, 1);
    }
  }
}

/* Section-picker overlay — shown ONLY while SHIFT is held. One row per
 * SECTION (coarse jumps; plain jog browses every bank overlay-free), each
 * carrying its section's icon right-aligned. Shift+jog moves the highlight;
 * releasing shift leaves you on that section's first bank. */
function drawBankPicker(ctx, s) {
  if (!shiftHeld(s)) return;
  const items = JUMP_SECTIONS;
  const active = activeSection(s.bank);
  const x = 4, y = 2, w = ctx.width - 8, h = ctx.height - 4;
  ctx.fillRect(x, y, w, h, 0);   // clear the screen beneath
  ctx.drawRect(x, y, w, h, 1);   // popup frame
  const rowH = 8, listY = y + 3, visible = 7;
  // Scroll so the active row stays in view (centered where possible).
  let top = active - Math.floor(visible / 2);
  top = Math.max(0, Math.min(Math.max(0, items.length - visible), top));
  for (let r = 0; r < visible; r++) {
    const i = top + r;
    if (i >= items.length) break;
    const ry = listY + r * rowH;
    const sel = i === active;
    if (sel) ctx.fillRect(x + 2, ry - 1, w - 6, rowH, 1);
    ctx.print(x + 4, ry, items[i].name, sel ? 0 : 1);
    const icon = BANK_ICONS[items[i].bank];
    if (icon) drawBankIcon(ctx, x + w - iconW(icon) - 7, ry, icon, sel ? 0 : 1);
  }
  // Right-edge scrollbar: track + a thumb sized/positioned to the window.
  const trackY = listY - 1, trackH = visible * rowH;
  const thumbH = Math.max(4, Math.round(trackH * visible / items.length));
  const denom = Math.max(1, items.length - visible);
  const thumbY = trackY + Math.round((trackH - thumbH) * top / denom);
  ctx.fillRect(x + w - 2, trackY, 1, trackH, 1);
  ctx.fillRect(x + w - 3, thumbY, 2, thumbH, 1);
}

/* ---- movy-style widget renderers ---- */

/* Layout: 8px header (Chunky Sans 6 text) + blank row + the indicator bar,
 * then two 16px widget rows each with its 7px label strip DIRECTLY beneath
 * (the knob circle is 15px in the 16px cell, so knobs keep a 1px visual
 * gap; squares sit flush):
 * hdr 0-7 (text 1-6) | blank 8 | bar 9 (+10 active) | gap 11 |
 * w0 12-27 | lbl0 28-34 | gap 35-39 | w1 40-55 | lbl1 56-62 | blank 63. */
const ROW0_Y = 12, LBL0_Y = 28, ROW1_Y = 40, LBL1_Y = 56;
const CELL_W = 32, KW = 20, KH = 16, LBL_H = 7;

function drawCircleBorder(ctx, cx, cy, r) {
  let x = r, y = 0, err = 0;
  while (x >= y) {
    if (y === 0) {
      // Cardinal extremes tucked in by 1: the raw midpoint circle leaves a
      // single pixel poking out at the exact top/bottom/left/right; plotting
      // them at r-1 sits flush with the neighbouring rows/columns instead.
      ctx.setPixel(cx + x - 1, cy, 1); ctx.setPixel(cx - x + 1, cy, 1);
      ctx.setPixel(cx, cy + x - 1, 1); ctx.setPixel(cx, cy - x + 1, 1);
    } else {
      ctx.setPixel(cx + x, cy + y, 1); ctx.setPixel(cx + y, cy + x, 1);
      ctx.setPixel(cx - y, cy + x, 1); ctx.setPixel(cx - x, cy + y, 1);
      ctx.setPixel(cx - x, cy - y, 1); ctx.setPixel(cx - y, cy - x, 1);
      ctx.setPixel(cx + y, cy - x, 1); ctx.setPixel(cx + x, cy - y, 1);
    }
    y++;
    if (err <= 0) err += 2 * y + 1;
    if (err > 0) { x--; err -= 2 * x + 1; }
  }
}

/* Arc knob: circle + a pointer line sweeping 300 degrees (210 -> 510).
 * Bipolar cells get a 12-o'clock center tick inside the dial. */
function drawArcKnob(ctx, kx, ky, norm, bipolar) {
  const cx = kx + 10, cy = ky + 7, r = 7;
  drawCircleBorder(ctx, cx, cy, r);
  if (bipolar) ctx.fillRect(cx, cy - r + 1, 1, 2, 1);
  // Pointer stops at r-1 so it meets the tucked-in border, never past it.
  const rad = (210 + norm * 300) * Math.PI / 180;
  const ex = Math.round(cx + (r - 1) * Math.sin(rad));
  const ey = Math.round(cy - (r - 1) * Math.cos(rad));
  plotLine(ctx, cx, cy, ex, ey, 1);
}

/* Horizontal bar filling left->right — the movy binary widget (toggles). */
function drawHBar(ctx, kx, ky, norm) {
  ctx.fillRect(kx + 1, ky + 4, 18, 1, 1);
  ctx.fillRect(kx + 1, ky + 10, 18, 1, 1);
  ctx.fillRect(kx + 1, ky + 4, 1, 7, 1);
  ctx.fillRect(kx + 18, ky + 4, 1, 7, 1);
  const fillW = Math.round(norm * 16);
  if (fillW > 0) ctx.fillRect(kx + 2, ky + 5, fillW, 5, 1);
}

/* Vertical bar filling bottom->up — mix/level feel (env Vel cells). */
function drawVBar(ctx, kx, ky, norm) {
  ctx.fillRect(kx + 6, ky + 1, 8, 1, 1);
  ctx.fillRect(kx + 6, ky + 14, 8, 1, 1);
  ctx.fillRect(kx + 6, ky + 1, 1, 14, 1);
  ctx.fillRect(kx + 13, ky + 1, 1, 14, 1);
  const fillH = Math.round(norm * 12);
  if (fillH > 0) ctx.fillRect(kx + 7, ky + 2 + (12 - fillH), 6, fillH, 1);
}

/* Framed square with the enum value as up to two 3-char 5x3 lines
 * (or a single provided square label). */
function drawEnumSquare(ctx, kx, ky, text, sqText) {
  ctx.drawRect(kx, ky, KW, KH, 1);
  const lines = sqText != null ? [String(sqText), ""] : enumSquareLines(text);
  const inner = KW - 2;
  const totalH = lines[1].length > 0 ? 11 : 5;
  const startY = ky + 1 + Math.floor((KH - 2 - totalH) / 2);
  const w1 = pf3Width(lines[0]);
  pf3Print(ctx, kx + 1 + Math.floor((inner - w1) / 2), startY, lines[0], 1);
  if (lines[1].length > 0) {
    const w2 = pf3Width(lines[1]);
    pf3Print(ctx, kx + 1 + Math.floor((inner - w2) / 2), startY + 6, lines[1], 1);
  }
}

/* Framed square with a single centered 5x3 value ("+2", "6"). */
function drawValSquare(ctx, kx, ky, text) {
  ctx.drawRect(kx, ky, KW, KH, 1);
  const w = pf3Width(text);
  pf3Print(ctx, kx + 1 + Math.floor((KW - 2 - w) / 2), ky + 1 + Math.floor((KH - 2 - 5) / 2), text, 1);
}

function normOf(ctx, cell) {
  const frac = (getRaw(ctx, cell) - cell.min) / (cell.max - cell.min);
  return Math.max(0, Math.min(1, frac));
}

/* Which movy widget a cell kind renders as. */
function widgetFor(cell) {
  if (cell.kind === "blank") return "blank";
  if (cell.kind === "waveenum") return "wave";
  if (cell.kind === "enum") return cell.options.length <= 2 ? "hbar" : "enumsq";
  if (cell.kind === "octave" || cell.kind === "count") return "valsq";
  if (cell.kind === "bipolar") return "arcbip";
  if (cell.kind === "fader") return "vbar";
  return "arc"; // unipolar
}

function drawWidget(ctx, col, rowY, cell) {
  const kx = col * CELL_W + Math.floor((CELL_W - KW) / 2);
  const style = widgetFor(cell);
  if (style === "blank") return;
  if (style === "wave") return drawWaveBox(ctx, kx, rowY, cell.shapes[getRaw(ctx, cell) - cell.min] || "sine");
  if (style === "hbar") return drawHBar(ctx, kx, rowY, normOf(ctx, cell));
  if (style === "vbar") return drawVBar(ctx, kx, rowY, normOf(ctx, cell));
  // cell.sqText(ctx): dynamic single-line square label (beats the static
  // per-option cell.sq array; e.g. "1234" for a reorder permutation).
  if (style === "enumsq") return drawEnumSquare(ctx, kx, rowY, formatCell(ctx, cell).text, cell.sqText ? cell.sqText(ctx) : (cell.sq ? cell.sq[getRaw(ctx, cell) - cell.min] : null));
  if (style === "valsq") return drawValSquare(ctx, kx, rowY, cell.sqText ? String(cell.sqText(ctx)) : formatCell(ctx, cell).text);
  drawArcKnob(ctx, kx, rowY, normOf(ctx, cell), style === "arcbip");
}

/* Label strip cell: the param NAME normally; while that knob is touched the
 * cell inverts and shows the live VALUE instead (movy's signature swap).
 * Rendered in the movy proportional font (mvPrint), like movy's own labels. */
function drawLabelCell(ctx, col, lblY, cell, touched) {
  let text = String(touched ? formatCell(ctx, cell).text : cell.label);
  while (text.length > 0 && mvWidth(text) > CELL_W - 2) text = text.slice(0, -1);
  const tw = mvWidth(text);
  const tx = Math.round(col * CELL_W + CELL_W / 2 - tw / 2);
  if (touched) {
    ctx.fillRect(col * CELL_W, lblY, CELL_W, LBL_H, 1);
    mvPrint(ctx, tx, lblY + 1, text, 0);
  } else {
    mvPrint(ctx, tx, lblY + 1, text, 1);
  }
}

function dottedV(ctx, x, y0, y1) {
  const lo = Math.min(y0, y1), hi = Math.max(y0, y1);
  for (let y = lo; y <= hi; y += 2) ctx.setPixel(x, y, 1);
}

/* Full-width ADSR graphic across a widget row (movy envelope.ts): A drives the
 * peak x, D the sustain-start x, S the plateau level, R the tail-end x, with a
 * fixed gate-off reference so release is always visible. */
function drawEnvelopeRow(ctx, rowY, cells) {
  const nrm = (i) => (cells[i] ? normOf(ctx, cells[i]) : 0);
  const a = nrm(0), d = nrm(1), s = nrm(2), r = nrm(3);
  const baseY = rowY + KH - 2, topY = rowY + 1;
  const usableH = baseY - topY;
  const gateX = 88;
  const startX = 2;
  const peakX = startX + Math.round(a * 26);
  let sustStartX = peakX + 4 + Math.round(d * 24);
  if (sustStartX > gateX - 2) sustStartX = gateX - 2;
  const susY = baseY - Math.round(s * usableH);
  let relEndX = gateX + 4 + Math.round(r * 33);
  if (relEndX > ctx.width - 2) relEndX = ctx.width - 2;
  plotLine(ctx, startX, baseY, peakX, topY, 1);       // attack rise
  plotLine(ctx, peakX, topY, sustStartX, susY, 1);    // decay fall
  plotLine(ctx, sustStartX, susY, gateX, susY, 1);    // sustain plateau
  plotLine(ctx, gateX, susY, relEndX, baseY, 1);      // release fall
  dottedV(ctx, sustStartX, susY, baseY);
  dottedV(ctx, gateX, susY, baseY);
  ctx.fillRect(Math.max(0, peakX - 1), topY, 2, 2, 1);
  ctx.fillRect(sustStartX - 1, Math.max(rowY, susY - 1), 2, 2, 1);
  ctx.fillRect(gateX - 1, Math.max(rowY, susY - 1), 2, 2, 1);
  ctx.fillRect(Math.min(ctx.width - 2, relEndX - 1), baseY - 1, 2, 2, 1);
}

/* Single-cell waveform box (wavesel cells): one cycle of the live shape
 * with a dotted center baseline, in place of an enum square. */
function drawWaveBox(ctx, kx, ky, shape) {
  const x0 = kx + 1, spanW = KW - 2;
  const topY = ky + 2, botY = ky + KH - 3;
  const baseY = Math.round((topY + botY) / 2);
  const amp = (botY - topY) / 2;
  for (let x = x0; x <= x0 + spanW; x += 2) ctx.setPixel(x, baseY, 1);
  let px = x0, py = Math.round(baseY - shapeSample(shape, 0) * amp);
  for (let i = 1; i <= spanW; i++) {
    const y = Math.round(baseY - shapeSample(shape, i / spanW) * amp);
    plotLine(ctx, px, py, x0 + i, y, 1);
    px = x0 + i; py = y;
  }
}

/* Two-cell LFO waveform span (movy lfo-wave.ts): replaces the widgets of
 * cells viz.cell and viz.cell+1 (same row) with two cycles of the live
 * shape. bank.lfoViz = { cell, shape: {key, shapes[]} | "sine",
 *   phaseKey?, bipolar? (default true), retrigKey? }.
 * Baseline: dotted center line when bipolar, bottom line when unipolar;
 * retrigger on -> bold dot at the start of the line. */
function drawLfoWave(ctx, viz, cells) {
  const col = viz.cell % 4;
  const rowY = viz.cell < 4 ? ROW0_Y : ROW1_Y;
  const x0 = col * CELL_W + 1;
  const spanW = 2 * CELL_W - 2;
  const topY = rowY + 1, botY = rowY + KH - 2;
  const bipolar = viz.bipolar !== false;
  const baseY = bipolar ? Math.round((topY + botY) / 2) : botY;
  const amp = bipolar ? (botY - topY) / 2 : (botY - topY);
  let shape = typeof viz.shape === "string" ? viz.shape : "sine";
  if (viz.shape && viz.shape.key) {
    const i = parseInt(ctx.getParam(viz.shape.key) || "0", 10);
    shape = viz.shape.shapes[isNaN(i) ? 0 : i] || "sine";
  }
  let phase = 0;
  if (viz.phaseKey) {
    const pv = parseInt(ctx.getParam(viz.phaseKey) || "0", 10);
    phase = isNaN(pv) ? 0 : pv / KIT_PARAM_MAX;
  }
  for (let x = x0; x <= x0 + spanW; x += 2) ctx.setPixel(x, baseY, 1);
  const yAt = (i) => {
    const v = shapeSample(shape, (i / spanW) * 2 + phase);
    return bipolar ? Math.round(baseY - v * amp) : Math.round(botY - ((v + 1) / 2) * amp);
  };
  let px = x0, py = yAt(0);
  for (let i = 1; i <= spanW; i++) {
    const y = yAt(i);
    plotLine(ctx, px, py, x0 + i, y, 1);
    px = x0 + i; py = y;
  }
  if (viz.retrigKey && parseInt(ctx.getParam(viz.retrigKey) || "0", 10) > 0) {
    ctx.fillRect(x0, Math.max(topY, Math.min(botY - 2, yAt(0) - 1)), 3, 3, 1);
  }
}

/* Vertical bipolar step bar: full-width center baseline, fill growing UP
 * for + and DOWN for - (classic step-sequencer level display). */
function drawVStep(ctx, x, w, top, h, signed, fg) {
  const cyc = top + Math.floor(h / 2);
  ctx.fillRect(x, cyc, w, 1, fg);
  const half = Math.floor(h / 2);
  const mag = Math.round(half * Math.min(1, Math.abs(signed)));
  if (signed >= 0) { if (mag > 0) ctx.fillRect(x, cyc - mag, w, mag, fg); }
  else if (mag > 0) ctx.fillRect(x, cyc + 1, w, mag, fg);
}

/* Step-sequencer editor (the sub-page reached by jogging RIGHT from a bank
 * with `steps`; jog LEFT backs out) — echidna's design: the 8 knobs are a
 * row of step faders for the current page of 8 steps, playhead = the active
 * step's number underlined, steps past the count inactive (dashed). */
function drawStepEditor(ctx, bank, s) {
  const vals = stepVals(ctx, bank);
  const center = stepsCenter(bank);
  const count = stepCount(ctx, bank);
  const page = (s.sub || 1) - 1;
  const pageCount = Math.max(1, Math.ceil(count / 8));
  drawChrome(ctx, bank.label + " STEPS " + (page + 1) + "/" + pageCount, s);
  // touched step's signed value, right-aligned in the inverted header
  if (s.lastKnob >= 0 && page * 8 + s.lastKnob < count) {
    const gidx = page * 8 + s.lastKnob;
    const sv = vals[gidx] - center;
    const rd = "S" + (gidx + 1) + " " + (sv > 0 ? "+" : "") + sv;
    njPrint(ctx, ctx.width - 2 - njWidth(rd), 1, rd, 0);
  }
  const playhead = stepPlayhead(ctx, bank, count);
  const dY = HDR_H + 5, dBot = ctx.height - 2, dH = dBot - dY; // frame top clears the indicator bar
  const colW = Math.floor(ctx.width / 8);
  for (let k = 0; k < 8; k++) {
    const stepIdx = page * 8 + k;
    const x = k * colW;
    const active = stepIdx < count;
    const touched = k === s.lastKnob && active;
    if (!active) {
      const cyc = dY + Math.floor(dH / 2);
      for (let dx = 1; dx < colW - 2; dx += 2) ctx.setPixel(x + dx, cyc, 1);
      continue;
    }
    const numStr = String(stepIdx + 1);
    const nw = ctx.measureText(numStr);
    if (touched) ctx.fillRect(x + 1, dY - 1, nw + 2, 8, 1);
    const nfg = touched ? 0 : 1;
    ctx.print(x + 2, dY, numStr, nfg);
    if (stepIdx === playhead) ctx.fillRect(x + 2, dY + 6, nw, 1, nfg);
    const barTop = dY + 9, barH = dH - 9;
    drawVStep(ctx, x + 2, colW - 5, barTop, barH, (vals[stepIdx] - center) / center, 1);
  }
  // frame + column dividers, matching the param grid's lined look
  const fTop = dY - 2;
  ctx.drawRect(0, fTop, ctx.width, dBot - fTop + 1, 1);
  for (let c = 1; c < 8; c++) ctx.fillRect(c * colW - 1, fTop, 1, dBot - fTop + 1, 1);
}

/* Framed HUD popup card (for CONFIG.overlays value-HUDs — the wave/tune2
 * card pattern): clears + frames a centered card, prints title left +
 * value right, and returns the body rect for the overlay to fill. */
function hudCard(ctx, title, valueText) {
  const x = 6, y = 11, w = ctx.width - 12, h = 42;
  ctx.fillRect(x, y, w, h, 0);
  ctx.drawRect(x, y, w, h, 1);
  ctx.print(x + 3, y + 2, fitText(ctx, title, w - 40), 1);
  if (valueText != null) {
    const vtxt = String(valueText);
    ctx.print(x + w - 3 - ctx.measureText(vtxt), y + 2, vtxt, 1);
  }
  ctx.fillRect(x + 1, y + 9, w - 2, 1, 1);
  return { x: x + 2, y: y + 11, w: w - 4, h: h - 13 };
}

/* Scrolling option-list overlay while a >2-option enum cell is touched
 * (movy drawEnumOverlay): covers the 3 columns away from the touched knob,
 * selection centered + inverted. Toggles skip it (the hbar says it all). */
function drawEnumOverlay(ctx, cells, s) {
  const k = s.lastKnob;
  const cell = k >= 0 ? cells[k] : null;
  if (!cell || cell.kind !== "enum" || cell.options.length <= 2) return;
  const sel = getRaw(ctx, cell) - cell.min;
  const ovX = (k % 4) < 2 ? ctx.width - 3 * CELL_W : 0;
  const ovW = 3 * CELL_W, ovY = ROW0_Y, ovH = LBL1_Y + LBL_H - ROW0_Y;
  ctx.fillRect(ovX, ovY, ovW, ovH, 0);
  ctx.drawRect(ovX, ovY, ovW, ovH, 1);
  const ROW_H = 8, n = cell.options.length;
  const VISIBLE = Math.min(n, Math.floor((ovH - 2) / ROW_H));
  const half = Math.floor(VISIBLE / 2);
  const start = Math.max(0, Math.min(sel - half, n - VISIBLE));
  const listTop = ovY + Math.floor((ovH - VISIBLE * ROW_H) / 2);
  for (let i = 0; i < VISIBLE; i++) {
    const idx = start + i;
    if (idx >= n) break;
    const y = listTop + i * ROW_H;
    if (idx === sel) {
      ctx.fillRect(ovX + 2, y, ovW - 4, ROW_H, 1);
      ctx.print(ovX + 4, y + 1, cell.options[idx], 0);
    } else {
      ctx.print(ovX + 4, y + 1, cell.options[idx], 1);
    }
  }
  if (n > VISIBLE) {
    const trackH = VISIBLE * ROW_H;
    const thumbH = Math.max(3, Math.round(trackH * VISIBLE / n));
    const thumbY = listTop + Math.round((trackH - thumbH) * start / Math.max(1, n - VISIBLE));
    ctx.fillRect(ovX + ovW - 2, listTop, 1, trackH, 1);
    ctx.fillRect(ovX + ovW - 3, thumbY, 2, thumbH, 1);
  }
}

/* The per-bank frame: header + two widget/label rows; env banks swap row 0's
 * widgets for the full-width envelope graphic. */
function drawBankView(ctx, bank, cells, s) {
  const hdr = headerTextFor(ctx, bank, s, cells);
  drawChrome(ctx, hdr.text, s, hdr.centered);
  if (bank.env) {
    drawEnvelopeRow(ctx, ROW0_Y, cells);
    for (let col = 0; col < 4; col++) {
      if (cells[col]) drawLabelCell(ctx, col, LBL0_Y, cells[col], col === s.lastKnob);
    }
    for (let col = 0; col < 4; col++) {
      const cell = cells[4 + col];
      if (!cell) continue;
      drawWidget(ctx, col, ROW1_Y, cell);
      drawLabelCell(ctx, col, LBL1_Y, cell, (4 + col) === s.lastKnob);
    }
  } else {
    const viz = bank.lfoViz;
    for (let k = 0; k < 8; k++) {
      const cell = cells[k];
      if (!cell) continue;
      const col = k % 4, rowY = k < 4 ? ROW0_Y : ROW1_Y, lblY = k < 4 ? LBL0_Y : LBL1_Y;
      const inViz = viz && (k === viz.cell || k === viz.cell + 1);
      if (!inViz) drawWidget(ctx, col, rowY, cell);
      drawLabelCell(ctx, col, lblY, cell, k === s.lastKnob);
    }
    if (viz) drawLfoWave(ctx, viz, cells);
  }
  drawEnumOverlay(ctx, cells, s);
  // Module hooks: transient value-HUDs etc. Each fn(ctx, cells, s) draws on
  // top of the bank view (use hudCard for the standard popup frame).
  if (CONFIG.overlays) for (const fn of CONFIG.overlays) fn(ctx, cells, s);
}

/* ---- the overlay object ---- */

const bank_editor = {
  onOpen(ctx) {
    ctx.state.init = false; // force re-seed from the persisted value
    readState(ctx);
  },

  onMidi(ctx, payload) {
    const d = payload && payload.data;
    if (!d || d.length < 3) return;
    const s = readState(ctx);
    const status = d[0] & 0xF0;

    if (status === 0x90 || status === 0x80) { // capacitive touch: notes 0-7 knobs
      const note = d[1];
      if (note <= 7) s.lastKnob = (status === 0x90 && d[2] >= 64) ? note : -1;
      return;
    }
    if (status !== 0xB0) return;
    const cc = d[1], val = d[2];

    // CC-49 fallback for off-device runs; on device shift arrives via the
    // shadow_get_shift_held() SHM poll (the shim doesn't forward CC 49 here).
    if (cc === 49) { s.shift = val >= 64; s.jogAccum = 0; return; }

    if (cc === 14) { // jog turn: steps banks either way; SHIFT adds the overlay
      const jd = dirFromCC(val);
      if (jd) {
        if (shiftHeld(s)) {
          // Shift+jog: step the picker section-to-section (NAV_SENS detents
          // per step), landing on that section's first bank. Plain jog stays
          // 1:1 through every bank with no overlay.
          const nr = accumStep(s.jogAccum, jd, NAV_SENS);
          s.jogAccum = nr.accum;
          if (!nr.fire) return;
          const ni = clampBank(activeSection(s.bank) + jd, JUMP_SECTIONS.length);
          s.bank = JUMP_SECTIONS[ni].bank;
          s.sub = 0;
        } else {
          s.jogAccum = 0;
          // Step-editor sub-pages first (jog RIGHT into / deeper, jog LEFT
          // back out), then spill over to the next/previous bank.
          const subMax = subPageCount(ctx, BANKS[s.bank]);
          const sub = s.sub || 0;
          if (jd > 0 && sub < subMax) {
            s.sub = sub + 1;
          } else if (jd < 0 && sub > 0) {
            s.sub = sub - 1;
          } else {
            s.bank = clampBank(s.bank + jd, BANKS.length);
            s.sub = 0;
          }
        }
        ctx.setValue(String(s.bank));  // persist for re-open
        s.lastKnob = -1;
        s.stepSelKey = null;           // re-seed the step cursor on next edit
      }
      return;
    }

    if (cc < 71 || cc > 78) return;
    const k = cc - 71;
    const dir = dirFromCC(val);
    if (!dir) return;
    const bank = BANKS[s.bank];
    const cell = cellsFor(ctx, bank, s.sub || 0, s)[k];
    if (!cell || cell.kind === "blank") return;   // empty slot on this bank

    if (cell.kind === "steplvl") {
      // Step editor: set the engine's step cursor only when the target step
      // CHANGES, track the value in state so a sustained turn is ONE
      // blocking write per fire (echidna's sel/lvl protocol).
      if (cell.stepIdx >= stepCount(ctx, bank)) return; // inactive step
      s.lastKnob = k;
      const sr = accumStep(s.accum[k], dir, KIT_SENS);
      s.accum[k] = sr.accum;
      if (!sr.fire) return;
      const selKey = s.bank + ":" + cell.stepIdx;
      if (s.stepSelKey !== selKey) {
        ctx.setParam(bank.steps.sel, String(cell.stepIdx));
        s.stepSelKey = selKey;
        s.stepVal = stepVals(ctx, bank)[cell.stepIdx];
      }
      let sv = s.stepVal + dir;
      if (sv < 0) sv = 0;
      if (sv > stepsMax(bank)) sv = stepsMax(bank);
      if (sv !== s.stepVal) { ctx.setParam(bank.steps.lvl, String(sv)); s.stepVal = sv; }
      return;
    }
    s.lastKnob = k;

    // All kinds (incl. enum) step-and-CLAMP; accumulate cell.sens detents
    // per step (knob feel + fewer blocking writes).
    const cr = accumStep(s.accum[k], dir, cell.sens || 2);
    s.accum[k] = cr.accum;
    if (!cr.fire) return;
    // Read + step in the native-int domain (getRaw applies get/parse hooks);
    // write via cell.set (local cells) or the wire format (cell.format).
    const cur = getRaw(ctx, cell);
    let nv = cur + dir * cell.step;
    if (nv < cell.min) nv = cell.min;
    if (nv > cell.max) nv = cell.max;
    if (nv === cur) return;
    if (cell.set) cell.set(ctx, nv);
    else ctx.setParam(cell.key, cell.format ? String(cell.format(nv)) : String(nv));
  },

  draw(ctx) {
    // One-time per-ctx install (guarded; draw runs every frame).
    if (!ctx._pfInstalled) {
      // (1) Text via the 5x5 pixel-font (the host's native OLED font has
      // different glyphs/metrics). Override print + measureText -> the layout
      // code routes every string through these.
      ctx.print = function (x, y, text, color) { pfPrint(ctx, x, y, text, color ? 1 : 0); };
      ctx.measureText = function (str) { return pfWidth(str); };
      // (2) getParam cache. On device each ctx.getParam is a ~2.6ms blocking
      // SHM round-trip, and the layout reads one per cell EVERY frame. Cache
      // reads; write-through on setParam so knob turns reflect instantly; and
      // full-refresh a couple times/sec to catch external changes (preset load).
      var rawGet = ctx.getParam, rawSet = ctx.setParam;
      ctx._pcache = {};
      ctx.getParam = function (k) {
        if (Object.prototype.hasOwnProperty.call(ctx._pcache, k)) return ctx._pcache[k];
        var v = rawGet.call(ctx, k);
        ctx._pcache[k] = v;
        return v;
      };
      var stepKeys = {};
      for (var bi = 0; bi < BANKS.length; bi++) {
        if (BANKS[bi].steps) { stepKeys[BANKS[bi].steps.sel] = BANKS[bi].steps.csv; stepKeys[BANKS[bi].steps.lvl] = BANKS[bi].steps.csv; }
      }
      ctx.setParam = function (k, v) {
        var r = rawSet.call(ctx, k, v);
        ctx._pcache[k] = String(v);   // reflect the write now
        if (stepKeys[k]) delete ctx._pcache[stepKeys[k]];  // sel/lvl writes dirty the CSV mirror
        // CONFIG.writeInvalidates(key) -> true = flush everything (preset
        // load), array = drop those keys (include key itself when the engine
        // may not land on the written value — select skip-walks), else null.
        // Caching a value the engine rewrote is the classic desync bug.
        if (CONFIG.writeInvalidates) {
          var inv = CONFIG.writeInvalidates(k);
          if (inv === true) ctx._pcache = {};
          else if (inv) for (var ii = 0; ii < inv.length; ii++) delete ctx._pcache[inv[ii]];
        }
        return r;
      };
      ctx._cacheTick = 0;
      ctx._pfInstalled = true;
    }
    // Periodic full refresh (~2x/sec) so external param changes surface.
    if ((ctx._cacheTick = (ctx._cacheTick + 1) % 24) === 0) ctx._pcache = {};

    const s = readState(ctx);
    const bank = BANKS[s.bank];
    if (bank.steps && (s.sub || 0) >= 1) drawStepEditor(ctx, bank, s);
    else drawBankView(ctx, bank, cellsFor(ctx, bank, 0, s), s);
    drawBankPicker(ctx, s);
  },

  _test: Object.assign({
    BANKS, JUMP_SECTIONS, activeSection, NAV_SENS, shiftHeld,
    dirFromCC, clampBank, accumStep,
    formatCell, DEFAULTS, kToggleLabels,
    drawBankIcon, BANK_ICONS, ICON_W, iconW,
    widgetFor, enumSquareLines, pf3Width, CONFIG,
    cellsFor, headerFor, headerTextFor, getRaw, subPageCount, stepCells, stepVals, shapeSample, hudCard
  }, CONFIG.testExports || {})
};


globalThis.bank_editor = bank_editor;
})();
